#!/usr/bin/env bash

SPLUNK_HOST=
SPLUNK_TOKEN=
SPLUNK_SOURCETYPE=
SPLUNK_SOURCE=
DGS_MSG_SIZE=512
DGA_MSG_COUNT=10000000
DGA_EPS=0
CONTAINER_COUNT=1
GZIP=false
FORMAT=inline
GZIP_LEVEL=-1
#SPLUNK_LOGGING_DRIVER_POST_MESSAGES_BATCH_SIZE
